kind: pipeline
type: docker
name: integration

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands: 
      - dotnet build Calculator.csproj

  - name: test
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands: 
      - cd Tests
      - dotnet test
